import type { NextConfig } from "next";
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./i18n/request.ts');

const nextConfig: NextConfig = {
  typescript: {
    // The .next/dev/types/validator.ts auto-generated by Next.js 16 typed-routes
    // has a false-positive error with top-level [locale] dynamic segments.
    ignoreBuildErrors: true,
  },
};

export default withNextIntl(nextConfig);
